### ISSUE TITLE
A little typo on the document

### ISSUE THREAD

**Issue by yujiangshui** [keajs/kea#101]
https://kea.js.org/

![image](https://user-images.githubusercontent.com/2942913/66725082-27ac1f80-ee8a-11e9-8744-a04cc4c3887d.png)

Forgot to delete the `()`?

**Comment by mariusandra** [comment]
You're right! Thanks for catching it! 
Would you like to submit a PR to the [kea-website](https://github.com/keajs/kea-website) repository to fix the issue?

**Comment by yujiangshui** [comment]
@mariusandra of course, my pleasure https://github.com/keajs/kea-website/pull/11

**Comment by mariusandra** [comment]
Thank you! The PR is merged and the new docs should be up soon.
