### ISSUE TITLE
Invalid hook call with useActions or useValues

### ISSUE THREAD

**Issue by KelvinCS** [keajs/kea#102]
Hi, congratulations for the project! Kea has been my go to when starting a new project.

I'm having an issue concerning the usage of hooks on the new version:

```Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

The code is like that
```
export default function Movies() {
  const { fetchMovies } = useActions(logic);
  const { movies } = useValues(logic);

  useEffect(() => fetchMovies());

  return <ContentList content={movies}></ContentList>;
}
```

**Comment by KelvinCS** [comment]
The code is like that:

**Comment by KelvinCS** [comment]
The code is like that:

export default function Movies() {
  const { fetchMovies } = useActions(logic);
  const { movies } = useValues(logic);

  useEffect(() => fetchMovies());

  return <ContentList content={movies}></ContentList>;
}

**Comment by mariusandra** [comment]
Hey! Thanks :)

Regarding the error, this is weird. I see nothing wrong with your code. Some things to ponder:
- How are you using the `<Movies />` component? For example calling it as a function (`const jsx = Movies()`) will break things.
- If you remove any of the lines in the component, will it work/break?
- Could you somehow have mismatching versions of React like the error says? E.g. some library that includes react through `dependencies` in package.json?

It's hard to tell, sorry :)

**Comment by KelvinCS** [comment]
The issue was not related to kea.
I've tried other libraries that exposes custom hooks and the same happened. The issue was related to `electron-webpack`, I guess it exposes more than one versions of React.
