### ISSUE TITLE
Unit test examples for logics (v2)?

### ISSUE THREAD

**Issue by davidkcyip** [keajs/kea#107]
Hi @mariusandra 

First of all, I'm loving Kea. Am currently integrating Kea into a fresh project for a start-up. Was wondering if you had any examples of unit tests for logics?

**Comment by mariusandra** [comment]
Hey @davidkcyip ! Great question and glad you hear Kea is working well for you!

Inspired by your question I just wrote a quick doc about 
[unit testing logic](https://kea.js.org/docs/guide/testing). Please let me know if it contains the information that you were looking for or if I can help with something else! :)

**Comment by davidkcyip** [comment]
Hey @mariusandra,

Thanks for this! It's mostly what I'm looking for. Do you have any recommendation on testing listeners that call an API endpoint?

**Comment by mariusandra** [comment]
Hey, I guess you should just [mock](https://jestjs.io/docs/en/mock-functions.html) the API with the tools jest provides and then use kea-waitfor to assure the corresponding success/failure actions get called.

**Comment by davidkcyip** [comment]
@mariusandra Thanks, I successfully wrote some unit tests. Thanks for your help.
