### ISSUE TITLE
Multiple stores configured in Redux Devtools

### ISSUE THREAD

**Issue by josephmr** [keajs/kea#111]
I noticed that when configuring Kea as per the [installation instructions][1] I ended up with 2 stores in my devtools. After a little digging I noticed that [`resetContext()`][2] is called internally just when including the library.

Based on very minor testing of commenting that line out, things still work as I expect and I only see a single store entry in the devtools.

I don't believe the extra store entry has any negative impacts; however, it was confusing seeing two stores and sometimes I have to manually switch to the actual active store when using the devtools. If there is some internal reason requiring `resetContext()` to be called simply for importing the library then maybe this side effect could be mentioned in the documentation.

-----

## Reproduction Steps
1. Start with a blank create-react-app
2. install kea deps `npm install --save kea reselect redux react-redux
3. require kea in index.js `const {resetContext, getContext} = require('kea');

    I'm using require instead of import here to avoid the dead code getting tree shaken

4. Run app and observe an empty store in redux devtools even though we haven't called `resetContext()`
5. Add call to `resetContext()` before render
6. Run app and observe 2 stores in the redux devtools

[1]: https://kea.js.org/docs/installation/instructions
[2]: https://github.com/keajs/kea/blob/3e7d664b53d2325db0b3873cbceebe25aac749c1/src/context/index.js#L9
![image](https://user-images.githubusercontent.com/28637598/88087823-8314e780-cb57-11ea-947a-7993608eccf2.png)

**Comment by sanchezweezer** [comment]
Same thing

**Comment by mariusandra** [comment]
Hey! `resetContext` has been called when the library is initialized for a while now. However starting with 2.0, we also create a new store by default in it. This is to ease setup of the library, so when you're not using any plugins, you can even skip calling `resetContext`.

Unfortunately I hadn't considered this devtool case. I'll try to find a solution before 2.2 hits the shelves. Thanks for reporting!

**Comment by mariusandra** [comment]
This should be fixed in `2.2.0-rc.2`.
