### ISSUE TITLE
Kea with graphQL/Apollo

### ISSUE THREAD

**Issue by Mukeshsharmami** [keajs/kea#112]
My app uses graphQL/Apollo and for state management I use [https://www.npmjs.com/package/apollo-cache-inmemory](url) but now it has become difficult manage state with just that.

I have thought of migrating it to kea and I see [https://kea.js.org/docs/introduction/what-is-kea#what-is-kea-not-good-for](url) 

Can anyone tell me, what problems I might run into if I migrate ?

**Comment by mariusandra** [comment]
Hey! The line in the docs was more in the spirit of "Apollo already supports local state, so you probably don't need kea". In case you feel that Apollo doesn't support local state *enough*, I could update the docs :).

As for problems you might run into, it's kind of hard to tell. There shouldn't be more problems compared to integrating pure Redux with Apollo. Kea is probably even less problematic.

Unfortunately I don't have any real experience with Apollo, but people have been running both apollo and kea successfully in the past (["I just tried and it works perfectly!"](https://github.com/keajs/kea/issues/18)), so I don't expect you to have any real problems. I'm not sure how effortless the handoff between apollo and kea would be (e.g. using the results of a query in a kea logic), but again it doesn't sound like anything that complicated.

Loosely related: I also once built a small plugin to add graphql support inside Kea with Apollo: https://kea.js.org/docs/playground/gists#kea-graphql  ... but that project didn't reach completion before I had to move on.

In case you decide to experiment with this, please share how it goes!


PS, there's something broken with the links in your comment. I had to copy/paste them.
