### ISSUE TITLE
How trigger a boolean action?

### ISSUE THREAD

**Issue by vmkevv** [keajs/kea#114]
Sorry for asking here, but I can't find any response anywhere.

I know if an action requires no params we can just put a boolean as value. Something like this.

```js
const logic = kea({
  actions: {
    fireAction: true,
  }
})
```

How can I fire it in a react component? I have this:

```js
const { fireAction } = useActions(logic);
//  after
fireAction() // this doesn't work
```
But I can't call it because it's not a function, so no action is fired. Any suggestion?

**Comment by mariusandra** [comment]
Hey! This is weird. The code you gave works fine for me. Here's a sandbox with it: https://codesandbox.io/s/kea-starter-forked-sp7fj?file=/src/app.js

**Comment by vmkevv** [comment]
Oh, yep, I just realized that it works, but when you use TS, boolean action gets the `never` type.

```ts
import { kea, MakeLogicType } from 'kea';

interface Values {
  // some values
}

interface Actions {
  logout: boolean;
}

const authLogic = kea<MakeLogicType<Values, Actions, null>>({
  actions: {
    logout: true,
  },
  defaults: {
    // some defaults
  },
  reducers: {
    // some reducers
  },
  listeners: ({ actions }) => ({
    someListener: async () => {
      // here I do some async actions and try to fire the actions.logout()
      actions.logout();
      // ^^^^ ts-error
    },
  }),
});

export default authLogic;
```
TS gives me the next error message:
```
This expression is not callable.
  Type 'never' has no call signatures.ts(2349)
```

PD: Sorry for not being specific about TS, I just thought it'll not work in JS as well

**Comment by chapterjason** [comment]
@vmkevv Just as a hint, you should define the action itself as noop function.

```typescript
interface Actions {
  logout: () => void;
}
```
and keep the action itself as `true` in the `kea` function.

```
const authLogic = kea<MakeLogicType<Values, Actions, Props>>({
  actions: {
    logout: true,
  },
})
```

**Comment by vmkevv** [comment]
Yea, that just works, thank you!
