### ISSUE TITLE
How to keep logics mounted even after react component unmounted

### ISSUE THREAD

**Issue by karthik-hr** [keajs/kea#117]
Is there a way to prevent un-mounting logic when react component is unmounted.
maybe like in event beforeUnmount i can execute some condition and say, I don't want to unmount this logic.
This will help us to use browser back and forward navigations and previous page will be in the state where we left.

**Comment by mariusandra** [comment]
Hey @karthik-hr , when a react component is unmounted, all logic that is connected to it will also be unmounted. If any component still uses a logic, it won't be unmounted.

Thus the best way to ensure a logic remains mounted is to mount it on a higher level in a component that doesn't get unmounted.

For example, a common practice is to use the [`useMountedLogic`](https://kea.js.org/docs/api/hooks#usemountedlogic) hook for really global logic, like `accountLogic`:

```js
import React from 'react'
import { useMountedLogic } from `kea`

function App() {
  useMountedLogic(userLogic)
  return <Provider><Router>...</Router></Provider>
}
```

That's the pattern I've used and it works quite well. 

There's currently no hook you can use to avoid unmounting a logic, however [this discussion](https://kea.js.org/docs/guide/advanced) about the logic lifecycle could provide some more context.
