### ISSUE TITLE
webworker support

### ISSUE THREAD

**Issue by kesavkolla** [keajs/kea#118]
Since kea is fully a logical layer is it possible to run the kea entirely from a worker? This makes kea completely separated from react UI thread.

**Comment by mariusandra** [comment]
Hey, it's theoretically possible, but it won't give you any real world benefits. Web worker run in a separate thread and only communicate via message passing. This adds enough overhead to basically neglect any performance wins you might get. 

Search for "redux webworker" to find examples of people trying this in the past, such as [this one](https://medium.com/front-end-weekly/off-main-thread-react-redux-with-performance-ba92b241ac8d) (medium link, open incognito to pass paywall)

**Comment by kesavkolla** [comment]
Web worker may be a bad use case. I used that use case to present complete decoupleness. Basically logic layer is not tied to react UI to me that is power in itself. In that case the same logic layer can be plugged to other UI layers like mobile in react native or even other UI in vuejs etc...

**Comment by mariusandra** [comment]
Indeed, Kea can be used totally without React. Here are some examples of using logics directly: https://kea.js.org/docs/guide/advanced
