### ISSUE TITLE
React native fast refresh support

### ISSUE THREAD

**Issue by sanchezweezer** [keajs/kea#119]
after edit file with logic (then it mounted) in expo it fails on fast refresh, because of fast refresh mechanism.

<img width="562" alt="Screenshot 2020-12-19 at 20 46 19" src="https://user-images.githubusercontent.com/19321990/102695883-413db980-423b-11eb-8ce5-e8693306a266.png">

**Comment by mariusandra** [comment]
Documenting that I'm seeing the same errors with fast refresh using create react app (using the [Kea CRA template](https://kea.js.org/docs/installation/instructions#shortcut-cra-template)). 

The solution for CRA for now is to add `FAST_REFRESH=false` to `.env` unfortunately.

I'd love to solve this though. Right now it seemed that React or something is just calling the cleanup function of `useEffect` inside `useMountedLogic` inside `useValues`, which then removes the values from redux. I'm not sure why as hooks shouldn't change with fast refresh.

**Comment by mariusandra** [comment]
I found [a fix](https://github.com/keajs/kea/commit/6b22ee79a22c2004ce17024bc209dbea2d6cc6d9) for the crashing. I'll release it with Kea 2.4 as soon as I track down one last issue. With the patch applied, if using `React.StrictMode` logics just won't refresh. Without strict mode, everything works. We won't hot-replace logic, but it'll be unloaded and loaded as needed. I think that's good enough for now :)

**Comment by mariusandra** [comment]
Kea 2.4 is out with support for this. In case logics don't reload after a change, just disable React.StrictMode for now. :|
