### ISSUE TITLE
Documentation gap for keyed logic files with paths

### ISSUE THREAD

**Issue by constancecchen** [keajs/kea#126]
Hey hey! First of all thanks so much for all your amazing work on Kea @mariusandra, you rock :)

I was struggling a bit with figuring out why keying my logic file with a path wasn't working. It seemed to be following the example in https://kea.js.org/docs/guide/additional#keyed-logic, so I was stumped. Here was my code:

```js
// Logic file
export const SomeLogic = kea({
  path: ['our_team', 'our_product', 'some_logic'],
  key: (props) => props.id,
 // ... etc
});

// Component file
export const SomeComponent = ({ id, values }) => {
  const logic = SomeLogic({ id, values });
  // ... etc
};
```

Fortunately, before I lost a ton of time banging my head against this, my awesome coworker pointed out that because I was setting a path, I needed to have the `key` in my path. It was documented in https://kea.js.org/docs/guide/debugging/#setting-the-path-manually, but not in the keyed logic docs, and it hadn't occurred to me there was a relationship between the two.

It would be awesome if you could update the "Keyed logic" docs section with either an example with keyed paths (i.e., `path: (key: string) => ['path', key]`) or to link to the above debugging page to help out other users who might end up in the same boat as me. Thanks so much!

**Comment by constancecchen** [comment]
Oh, also, if you'd rather have me open a PR myself with any documentation changes/suggestions, please let me know, I'm happy to do so!

**Comment by mariusandra** [comment]
Hey @constancecchen , thanks for bringing this up! I [made a small change](https://github.com/keajs/kea-docs/commit/0e36e604ece93d5d9201ce07b45d4dd9c0d7015b) to the docs to clarify this. Feel free to submit a PR next time as well :).

**Comment by constancecchen** [comment]
Thank you so much Marius!! That documentation looks perfect. You're amazing!
