### ISSUE TITLE
Passing MakeLogicType into the `.extend` API

### ISSUE THREAD

**Issue by constancecchen** [keajs/kea#129]
Heya Marius, sorry to bother you again!! 👋 Our team has run up into another use case where we'd love to use the [.extend()](https://kea.js.org/docs/guide/advanced#extending-logic) API to share some common listeners/state between 2 similar-ish logic files, but unfortunately we're blocked by typing being fairly broken once we start to use `.extend()`.

Here's an example commit of what I was hoping to use extend for: https://github.com/constancecchen/kibana/commit/e51b21c924df4fada6cc2832892f7ec3b82cb63a (I've left a few code comments highlighting the problematic type areas in that link).

For now, I've opted to instead use [explicit connections](https://kea.js.org/docs/guide/additional/#explicit-connections) (commit ref: https://github.com/constancecchen/kibana/commit/9e46d0e76c9ce0054f6bc67e6c4e9c6150b45810) which gets the typing working again and works excellently for this use case, where there's less than 5 shared values/actions and the 2 files have a minor amount of things in common.

`.extend()` would be super useful however for a couple of our other files, where the majority of the values/actions are shared and there's just 1 or two things that differ between views. I was hoping it might be less dev effort to support just [MakeLogicType](https://kea.js.org/docs/guide/typescript/#option-2-makelogictypev-a-p) (vs. kea-typegen) for the `.extend()` API by passing in some Typescript generics, but I'm definitely not a Typescript expert so could be way off base about that.

As always, thanks a million for your awesome work and let me know if I can elaborate further / help at all!

**Comment by mariusandra** [comment]
Hey Constance, thanks for the support! :)

I added support for passing the right `Type` into `logic.extend<Type>()` in Kea 2.4.1. 

However, this might not be the function you want to use. When you call `logic.extend()`, you're modifying the existing logic. In your case you're adding a bunch of actions/values onto `SchemaBaseLogic`. 

If you want more traditional inheritance a'la `class Cat extends Animal`, where all the actions/values from `SchemaBaseLogic` are cloned into `SchemaLogic`, and an independent set is cloned into all other logics that might inherit from `SchemaBaseLogic` in the future, then this was possible [with a workaround](https://github.com/keajs/kea/commit/1b7c2213affd9a39b80a0a80ec815eb7fab3c1ba#diff-dc713bc4e7edcefd21a17b30f9bd7d12ad77103badd0b3416d4f12091116d6c9). From Kea 2.4.2 however you can use `inherit` like so:

```ts
const SchemaLogic = kea<SchemaLogicType>({
  inherit: [SchemaBaseLogic],
  path: ['schema'],
  actions: {
    ...
  },
})
```

and the new `SchemaLogic` will have a clone of the `SchemaBaseLogic` actions, values and everything else.

...

However, even then you might want to just `connect` like you're doing now. That would be the case if `SchemaBaseLogic` has a listener to make a long API request, and all logics that inherit (like `SchemaLogic`) need the same data. If you use `connect`, the request will be made just once. If you use `inherit`, it'll be made once per logic that inherits.

Hope this helps :)

**Comment by constancecchen** [comment]
This looks awesome!!! Thanks so much as always Marius, not least for the super speedy turnaround time ❤️ I'll try to play around with both the new extend typing and awesome-looking `inherit` API here in a bit, but it may be a while (big release coming up!). Definitely feel free to consider this issue solved/closed for us, and I'll follow up if we run into any other typing/test shenanigans. Thanks again!

**Comment by mariusandra** [comment]
That's great, closing the issue :)
