### ISSUE TITLE
Better examples needed

### ISSUE THREAD

**Issue by mariusandra** [keajs/kea#13]
Hey, currently there is only one example in the guide: [TodoMVC](https://kea.js.org/examples/todos)

We need some more examples to showcase the functionality of `kea`, much like [SoundRedux](https://github.com/andrewngu/sound-redux) did for Redux.

Currently I can point to [my own startup](https://www.apprentus.com), a [freelance project](https://gsmtasks.eu/) (and a few others) or to an alpha-stage [open source data analytics platform](https://github.com/mariusandra/insights) when anyone asks for examples of projects that use kea in production. The last of the three has the source available, but is using an older version of kea.

Thus it would be great to have some fresh examples.

Is anyone up for the challenge of writing some?

Some ideas:
- soundclound client (is it shutting down?)
- github client
- HN client
- ... ?

Other ideas?

**Comment by ktmn** [comment]
Maybe an example or two could show versions with and without kea, so you can get a good idea what kea simplifies exactly.

**Comment by mariusandra** [comment]
I added the simplest [github example](https://kea.js.org/examples/github) I could think of.
The [entire codebase until here](https://github.com/keajs/kea-website/blob/8a155751b1b66901924477bcca813fe1f29918e4/app/scenes/examples/github/index.js) took 30min to write. That's how powerful the abstractions kea brings are 😄 🐦

**Comment by hvdklauw** [comment]
The github example made some things clearer, but having the username input separated from the github repositories would be nice so you can actually figure out how to use them across, for instance a user name input component, one that fetches the github repositories and the latest X tweets for the username.

**Comment by mariusandra** [comment]
@hvdklauw hey, that's a good idea! I'll see when I can write up something about it.

That said, this is definitely something that's possible. The final solution depends on the level of abstraction you need, but in short I'd separate the parts that fetch the tweets and repos into separate logic files, have them listen to the `setUsername` action (or some other `fetchTweets(username)` if it makes sense) and then connect those logic stores to your component to get the right props.

**Comment by mariusandra** [comment]
@hvdklauw Hey, I developed a simple example that asks HN and Github for details about a username.

You can see [the demo here](https://kea.js.org/guide/connected-services) and [the code here](https://github.com/keajs/kea-website/tree/master/app/scenes/guide/connected-services/services).

The guide for this chapter is not yet ready and the code is still messy, but does it the trick and should show how to achieve this. I'll clean it up and write about it in the coming days.

There is [one nuisance](https://github.com/keajs/kea-website/blob/50e604f6faaf0cb11fa9ea1567aecdb48232c2b6/app/scenes/guide/connected-services/services/index.js#L45) with the example though. You need to manually connect the sagas of the imported components, otherwise they will not be listening to actions. I hope to fix that in a future release.

In my own projects I've always connected all the sagas in a scene to the root component of the scene, to make sure they're always running. However that shouldn't be necessary once 0.20 comes out.

**Comment by mariusandra** [comment]
I released kea `v0.20`, which [no longer requires you to manually start connected sagas](https://github.com/keajs/kea-website/commit/8d1b96ffddc05cd55f98653663edba4d4862a09b). So the nuisance I mentioned in the previous comment is solved. 

In addition, if for example you render many instances of the same component, only one shared saga will be started for all of them. So assuming `<Slider />` is a component that has an attached logic store with a saga, previously this code would start 3 instances of the same saga. Now only one is started:

```js
<div>
  <Slider />
  <Slider />
  <Slider />
</div>
```

**Comment by therise3107** [comment]
@mariusandra Thank you for this awesome project! Some ideas I can think are:
 * To-Do app using Firebase API.
 * Simple Blog with User Authentication.
 I am going through the docs to create a simple client side boilerplate using webpack.

**Comment by danielmariz** [comment]
Adding more complex examples using sagas (controlling data via localstorage) and unit tests will be awesome too

**Comment by mariusandra** [comment]
Thank you all for your ideas! 

I added a new example and chapter to the guide: [Forms](https://kea.js.org/guide/forms). I hope it clarifies even more things :). I'll get to even more complicated examples in the future.

**Comment by neginbasiri** [comment]
@mariusandra  Thanks for Forms example. I am using same form twice in the page, apparently I need to ass key to kea (same way as dynamic counter example ). I couldn't find any example which shows how to use key or action for selectors. I'd appreciate if you add this to form example. Cheers

**Comment by mariusandra** [comment]
@neginbasiri Hey, if you're dynamically generating the form by returning a `kea({})` logic store from a function, you can also dynamically create the path. Something like this:

```js
function createCounterLogic({ fomName, ...options }) {
  return kea({
    path: () => ['kea', 'forms', formName],
    // ...
  })
}
```

or actually, just run createForm twice to create two instances of the same form.

That's all I can say for now. If you still have issues, show me some code and I can try to debug futher :)
