### ISSUE TITLE
pass component props to logic

### ISSUE THREAD

**Issue by SeifESlimene** [keajs/kea#133]
Hello,

Is there any possibility to pass a component prop to logic to use them as the default value for a reducer for example?

For Example,
I have a component B which has a parent component A, A pass to B a prop called foo,
I want that foo to become the default value for a reducer called values

export default kea({
  reducers: ({ actions }) => ({
    values: [**Here I want to use the prop foo passed from component A to component B**, PropTypes.object, {}],
  })
})

**Comment by mariusandra** [comment]
Sure, just do:

```js
export default kea({
  reducers: ({ actions, props }) => ({
    values: [props.foo, PropTypes.object, {}],
  })
})
```

**Comment by SeifESlimene** [comment]
Hello again,

Thank you but It doesn't work with me!
I made a little example and it works with a default value of '1' for the text reducer and when I change it to props. name it gives me an error.

You can check the sandbox here: 
https://codesandbox.io/s/kea-three-buttons-forked-wp6eo

**Comment by mariusandra** [comment]
Hey @SeifESlimene , sorry but I don't really see what you mean with that codesandbox. Is it a complete example? I'd gladly help if I could see what's broken. Right now I don't see any props usage at all.
