### ISSUE TITLE
Is there a way to use generics with `MakeLogicType` ?

### ISSUE THREAD

**Issue by JasonStoltz** [keajs/kea#134]
Something like:

```
type SomeLogicType<ItemType> = MakeLogicType<
  SomeLogicValues<ItemType>,
  SomeLogicActions<ItemType>
>;

export const SomeLogic = kea<SomeLogicType<ItemType>>({
```

Where `ItemType` is passed as a type parameter to `useValues` or something?

```
useValues<MyType>(SomeLogic)
```

**Comment by JasonStoltz** [comment]
I just wrapped it in a factory function and 👌 

```
export const getSomeLogic = <T>() => {
  return kea<SomeLogicType<T>>({
```

```
const logic = getSomeLogic<Foo>()();
```

**Comment by mariusandra** [comment]
That's a clever trick!

Not sure why it doesn't work for you though. 

<img width="650" alt="Screenshot 2021-07-23 at 21 29 27" src="https://user-images.githubusercontent.com/53387/126832034-0604c51d-26dc-48dc-ba6f-88d00de192f3.png">

![image](https://user-images.githubusercontent.com/53387/126832087-e661370c-33c5-4c3e-9e24-fa1b7de58366.png)

**Comment by JasonStoltz** [comment]
That does work. Sorry, to clarify, instead of a concrete type like `ItemType` in your example, I want it to be generic. So that the logic can work with *any* type. So one place where the logic is used it might work with strings, other places might work with numbers, etc.
