### ISSUE TITLE
Why do we want to use kea? And when?

### ISSUE THREAD

**Issue by FateRiddle** [keajs/kea#14]
I find the README is lacking this key concept explanation. So raise this issue here. 
I'm currently using a solution of redux + thunk + redux-promise-middleware,
why do I want to use kea and when?

**Comment by mariusandra** [comment]
Hey, thank you for bringing this to my attention!

Indeed the README is lacking. I did release the project under the mantra of "if you're not embarrassed by it, you released it too late". 

Ideally I would like some pages in the docs about kea vs setState, kea vs vanilla Redux, kea vs MobX, kea vs Apollo, etc. All PRs for this are welcome! :)

I will try to answer your question below.

The combination you specified only solves one part of the picture: creating and dispatching actions. This part is about interacting with Redux when Redux is on the receiving end of the data flow.

In addition to that, Kea provides a standardised way to interact with Redux when your React components are on the receiving end of the data flow.

Previously you had to hook all of it up yourself through redux's `mapStateToProps` and `mapActionsToProps`. This is no longer necessary. Just define your reducers, selectors and/or connected props and you're done. Your component will immediately get the data.

Also, kea's [`connect` helper](https://kea.js.org/guide/connected) is immensely powerful when your application's size grows. It allows you to glue together various parts of your app into a well functioning and readable whole - you always know what data comes from where.

All of that, and, reducing boilerplate are good reasons to use kea over redux + thunk + redux-promise-middleware IMHO. That said, YMMV!

**Comment by mariusandra** [comment]
Hey, I added a few descriptive points to the homepage about what Kea is. I couldn't use exactly the sentence @DarrylD quoted, but I hope what's now there will make the value proposition a bit clearer.  Closing this topic now. Feel free to reopen (or create a new issue) if you want to add or comment on something.
