### ISSUE TITLE
How to test `propsChanged` ?

### ISSUE THREAD

**Issue by paolodamico** [keajs/kea#149]
Would be great if we could document how to properly test the effects of `propsChanged`.

**Conceptual example (code does not work like this):**

```js
let logic = myLogic({
    foo: 'bar',
})
logic.mount()
await expectLogic(logic).toFinishAllListeners().toMatchValues({ isFooBar: true })

logic = myLogic({
    foo: 'baz',
})
await expectLogic(logic).toFinishAllListeners().toMatchValues({ isFooBar: false })
```

**Comment by mariusandra** [comment]
Hey @paolodamico, I made a [test like this](https://github.com/keajs/kea-test-utils/commit/10e175f549823c7dc814e18cf132607e4c90c642#diff-fc4c43dc9a08c29d6cdcb7e148761c45259391224c86a04714287b95bb56d605)... and it passes. 🤔 

What could be happening in your case could perhaps be:
- you matched some actions earlier, and now the values are stuck at the state right after the action. Try [`.clearHistory()`](https://keajs.org/docs/intro/testing/#clearhistory)
- there is a 0ms timeout before propsChanged is triggered. Perhaps that's not enough? Try a `.delay(1)`, or then waiting for the [`@KEA/FLUSH` action](https://github.com/keajs/kea/blob/396252db5c/src/react/hooks.ts#L112) that gets triggered after props change

Apologies for the lag 😅
