### ISSUE TITLE
Scaffolding : Not able to install dependency fsevents

### ISSUE THREAD

**Issue by kncs** [keajs/kea#15]
I would like to try kea and have an issue installing dependencies on ubuntu 14.04  (x64) using node v8.1.4 (npm v5.3.0). 

I get this error : **Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})**

How can we deal with it ?

**Comment by mariusandra** [comment]
Hey,

As a quick fix, you may open the `package.json` in the new project's folder and remove the line `"fsevents": "^1.1.2",`. Then run yarn again.

I'll think of a proper fix as soon as possible.

**Comment by kncs** [comment]
Ok thanks for the quick fix.

**Comment by mariusandra** [comment]
Hey, it appears this dependency was needed at all, as it should already be installed through `webpack-dev-server`. Not sure why it was there in the first place. I removed this line and cleaned up some other bugs in the `kea-example` repo that got cloned when scaffolding.
