### ISSUE TITLE
Link in About on GitHub repo is dead

### ISSUE THREAD

**Issue by matt-hensley** [keajs/kea#154]
The link in the About sidebar section on GitHub points to https://kea.js.org instead of https://keajs.org

Screenshot of the About section of the sidebar:
<img width="321" alt="Screen Shot 2023-03-27 at 9 22 58 PM" src="https://user-images.githubusercontent.com/130569/228102453-b3e77827-6322-4de9-afde-d362d7a2a916.png">

**Comment by mariusandra** [comment]
Thanks, fixed! :)
