### ISSUE TITLE
How to do something like router.pop()

### ISSUE THREAD

**Issue by Arun-chaitanya** [keajs/kea#155]
I can see I have actions like router.actions.push and router.actions.replace. But how to do POP action. Can you help @mariusandra

**Comment by mariusandra** [comment]
Sadly this is not possible. Not because of Kea, but since the browser's history api does not support this. Running `window.history.back()` might trigger it, but also not reliably if there's nothing in the history

**Comment by Arun-chaitanya** [comment]
Got it @mariusandra. Just a question though. In React Navigation, when you use the navigation.push() method to push a screen onto the stack and that screen is already present in the stack, it will result in a "stack reset." This means that all the screens above the duplicate screen in the stack will be removed (popped) from the stack, and the duplicate screen will appear as the topmost screen. 
Can we also provide an extra config option in our `router.actions.push`. Of course, it will be optional, and by default this can be false.

**Comment by mariusandra** [comment]
This seems like a pretty unique requirement, and unlike how navigation on the web works, so this likely shouldn't be part of the library. `kea-router` is just a light wrapper around the browser's history API, which [does not](https://stackoverflow.com/questions/17032415/javascript-browser-history-listing) tell you what pages the user visited.

The only real way I can think of doing this is:
- Keep track of the full history of all the pages in the router (track every push/pop/replace/location_changed event and update some list accordingly)
- When a page is visited that matches, run `history.go(-4)` or whichever number to go to that page. 
- Note that there's no guarantee that the browser history and the window history are really in sync. It's also not possible to get some callback every time the URL changed.
- Assuming you land in the right place, call `window.location.replace` with the current URL to clear the "forward history".
- There is more than one browser, and different extensions may change how the history works.

All of my years in this industry say that implementing the above is a bad idea, full of various unobvious edge cases that will give you a bad time. This inadvertently means that I'm not going to implement this as part of the library, as that would mean I'd have to deal with all the edge cases and support requests on an ongoing basis.

You are free to implement all of this as part of your own app if you choose of course. I don't think you'd need to modify Kea for this.

Hope this helps somehow :).

**Comment by Arun-chaitanya** [comment]
@mariusandra thanks for this information. This was very insightful. I guess you can close the issue now.
