### ISSUE TITLE
Selector types and limitation to only 11

### ISSUE THREAD

**Issue by iantbarker** [keajs/kea#159]
I'm typing a selector and I am doing this:

```
      selectors =>
        [
          selectors.filterTags,
          selectors.filterTopics,
          selectors.filterArtists,
          selectors.filterCategories,
          selectors.filterBios,
          selectors.filterApproved,
          selectors.filterPublic,
          selectors.filterSpeaker,
          selectors.filterWorshipLeaders,
          selectors.filterLanguages,
          selectors.filterSeries,
          selectors.filterAlbum,
          selectors.filterDates,
          selectors.customFilters,
        ],
```
but get an error: `Source has 14 element(s) but target allows only 11.`

In the types.ts file, the `SelectorTuple` type is using tuples which is where the limit comes from. 

Is there any way to increase that limit or how can I rework this selector to get around this limitation?

**Comment by mariusandra** [comment]
Hey, this probably needs a better fix, but as a quick improvement I added a few more rows to `types.ts`, bringing the number of supported input selector to 16 now.
