### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by raitucarp** [keajs/kea#16]
Why I have ```regeneratorRuntime is not defined``` error? I've installed regenerator-runtime and still nothing changes.

Note: I use create-react-app

**Comment by mariusandra** [comment]
Hey, I added a section to the [installation guide](https://kea.js.org/guide/installation) on how to get kea working with create-react-app.

To get rid of this error, you must specifically import the required `regenerator-runtime` endpoint, like so:

```
import "regenerator-runtime/runtime";
```

At least this helped me with the error.

Also, please upgrade to at least kea `0.19.13`.
