### ISSUE TITLE
Apollo & Stateless Components

### ISSUE THREAD

**Issue by wmhafiz** [keajs/kea#18]
Hi,
I'm really liking KeaJS and the abstractions that it brings to our code. 

However I would appreciate it if you could provide examples on how to integrate Apollo & GraphQL (perhaps use Graph.cool service for the backend) with Kea JS. How do we go about using HOC from apollo library within sagas inside Kea?

Also I'm wondering if Kea would play nice with stateless functional components (so that I can use recompose helper utils instead of using the Kea decorator syntax)?

(I'm still new to Redux/Sagas etc so please bear with me)

Thanks!

**Comment by mariusandra** [comment]
Hey! Thanks for the nice words!

Unfortunately I don't (yet) have any experience with Apollo or GraphQL, thus I can't fully answer your question. I do know that it is possible to add multiple HOCs on top of each other, so your code might look like:

```js
@graphql({ /* apollo options */ })
@kea({ /* kea options */ })
class MyComponent extends Component {
  render () {
    // kea props
    const { prop1, prop2 } = this.props
    // kea actions
    const { action1, action2 } = this.actions // or this.props.actions
    // apollo props and actions
    const { graphQL1, refetch } = this.props.data
  }
}

// or
export default graphql({ /* apollo options */ })(kea({ /* kea options */ })(MyComponent))
```

If kea is the loweset (innermost) wrapper around your component, you will have `this.actions` available. If it's higher than that, you need to use `this.props.actions`. Apollo seems to store its data in `this.props.data`, so in theory there should be no conflict.

That said, I have no idea if this will work in practice. Please let me know :).

How to configure the stores/providers that both work, I don't know... but as Apollo uses Redux under the hood, probably things will just work.

...

As for stateless functional components, these are possible, as they work with react-redux out of the box. The syntax is a bit clunky and looks like this: (copied from issue #7)

```js
export default kea({
  actions: () => ({
    action1: true,
    action2: false
  }),
  reducers: () => ({
    prop1: [...],
    prop2: [...]
  }),
  connect: {
    actions: [
      otherLogic, [
        'importedAction1'
      ]
    ],
    props: [
      otherLogic, [
        'importedProp1'
      ]
    ]
  },
  // ... other kea options
})(({
  prop1, prop2, importedProp1,
  // actions are always also passed in a prop called 'actions' 
  actions: { action1, action2, importedAction1 }
}) => (
  <div>
    <button onClick={action1}>{prop1}</button>
  </div>
))
```

Hope this helps :)

**Comment by wmhafiz** [comment]
I just tried and it works perfectly! Zero trouble integrating the stores either!
And with #19, im now able to create selectors from both apollo n kea props! 

Im so happy that this has reduce a lot of the boilerplate code & made my coding so much simpler!
More people should use KeaJS as its making redux world a better place!  👍

**Comment by mariusandra** [comment]
Hey, that's wonderful news!

And I agree, more people should use Kea! 😃  . So spread the word 😏

I added [a section](https://kea.js.org/api/component) in the API documentation about stateless functional components.

I'll write some documentation about Kea+Apollo (and kea vs setState/redux/mobx/dva/etc) within the next week. I'll keep this issue open until then.

**Comment by wmhafiz** [comment]
Awesome! Do consider writing a Medium article as well! It would help introduce this great library to the javascript community!

**Comment by mariusandra** [comment]
So... here's a [Medium article](https://medium.com/@mariusandra/kea-vs-setstate-redux-mobx-dva-jumpstate-apollo-etc-4aa26ea11d02) about Kea :).

I'll still keep the issue open until I manage to merge parts of it into the documentation.

**Comment by mariusandra** [comment]
I added a link to the medium article on the homepage. Closing this issue now.

**Comment by n-marshall** [comment]
Just for leaving some documentation about the second part of the question (Kea & HOCs) for anyone who would come read this topic in the future, here's the GithubSearch example from the docs, translated to use Stateless components and recompose : 

```javascript
const API_URL = "https://api.github.com";

const Loading = () => <div>Loading</div>;
const displayLoadingState = branch(
  ({ isLoading }) => isLoading,
  renderComponent(Loading)
);

const data = kea({
  actions: () => ({
    setUsername: username => ({ username }),
    setRepositories: repositories => ({ repositories }),
    setFetchError: message => ({ message })
  }),
  reducers: ({ actions }) => ({
    username: [
      "",
      PropTypes.string,
      {
        [actions.setUsername]: (_, payload) => payload.username
      }
    ],
    repositories: [
      [],
      PropTypes.array,
      {
        [actions.setUsername]: () => [],
        [actions.setRepositories]: (_, payload) => payload.repositories
      }
    ],
    isLoading: [
      false,
      PropTypes.bool,
      {
        [actions.setUsername]: () => true,
        [actions.setRepositories]: () => false,
        [actions.setFetchError]: () => false
      }
    ],
    error: [
      null,
      PropTypes.string,
      {
        [actions.setUsername]: () => null,
        [actions.setFetchError]: (_, payload) => payload.message
      }
    ]
  }),
  takeLatest: ({ actions, workers }) => ({
    [actions.setUsername]: workers.fetchRepositories
  }),
  workers: {
    *fetchRepositories(action) {
      const { setRepositories, setFetchError } = this.actions;
      const { username } = action.payload;

      yield delay(100); // debounce for 100ms

      const url = `${API_URL}/users/${username}/repos?per_page=250`;
      const response = yield window.fetch(url);

      if (response.status === 200) {
        const json = yield response.json();
        yield put(setRepositories(json));
      } else {
        const json = yield response.json();
        yield put(setFetchError(json.message));
      }
    }
  }
});

const ReposPure = ({ repositories, username, error }) =>
  repositories.length > 0
    ? <div>
        Found {repositories.length} repositories for user {username}!
        {repositories.map(repo =>
          <div key={repo.id}>
            <a href={repo.html_url}>{repo.full_name}</a>
            {" - "}
            {repo.stargazers_count} stars, {repo.forks} forks.
          </div>
        )}
      </div>
    : <div>
        {error ? `Error: ${error}` : "No repositories found"}
      </div>;

const Repos = compose(data, displayLoadingState, pure)(ReposPure);

const GithubSearchPure = ({ username, actions: { setUsername } }) =>
  <div>
    <h1> Github Search</h1>
    <input
      type="text"
      value={username}
      placeholder="Search for a github user..."
      onChange={e => setUsername(e.target.value)}
    />
    <div>
      <p />
      <Repos />
    </div>
  </div>;

const GithubSearch = compose(data, pure)(GithubSearchPure);
export default GithubSearch;
```

I'm starting out with both Kea and Stateless components / Recompose, but it's really pleasant to see how nice these parts play together (especially the ability to inject the same data into both the <GithubSearch> and the <Repos> )

I'll move on to Apollo and GraphQL next, and I plan to gather a few examples as I learn into a repo at https://github.com/n-marshall/kea-examples, but maybe there's an official kea examples repo I could contribute to instead ?

**Comment by mariusandra** [comment]
Hey @n-marshall, very cool and thanks for posting this example! :)

You could contribute these examples to the [kea-website](https://github.com/keajs/kea-website) repository. There's an "examples" subsection there that already has the regular github example.

An idea is to create a new page there called "stateless github" and add a bit of explanation as to how is it different from the regular github one.

That "examples" section has the capacity to host a lot of different examples, both big and small, so all code contributions there are very welcome! :)
