### ISSUE TITLE
Integration into existing project

### ISSUE THREAD

**Issue by patrick-jones** [keajs/kea#21]
I just stumbled across this project. I really like what you're doing here, but I find myself wondering if I could integrate kea into my already existing react/redux/saga project. I expect I would have many components that would need access to kea-based infrastructure as well as the manually wired stuff I already have. Is there an elegant way to combine these two? I suppose I could wrap my kea-generated stuff with `connect()` from react-redux, but it would be nice to have a cleaner option. 

If you have any suggestions, you might want to add it to the documentation.

**Comment by mariusandra** [comment]
Hey, in theory everything should just work and be able to interoperate. I'll improve the documentation on this front in the near future. However for some quick tips:

- When you define a kea logic store (`const myLogic = kea({ /* stuff */ })`), then you can always access the underlying redux actions, reducers, etc by just asking for them like `myLogic.actions.actionName` or `myLogic.selectors.selectorName` or just `myLogic.selector` to get all the reduces.
- You may always `connect` whatever selectors and use them to access anything in Redux, see the example [here in the API docs](https://kea.js.org/api/logic) under `connect`
- In the Kea reducers you may use any string as the key and if an action with this type is called, it will be matched. 
- You may access the sagas created for each logic store with `myLogic.saga`... and you may call whichever other sagas from your kea sagas. 

Hope this helps/clarifies a bit. If you have any more specific questions, I'll be happy to help.

**Comment by mariusandra** [comment]
Hi, I have added a section to the guide, titled [Migrating existing Redux applications](https://kea.js.org/guide/migration). This should clarify the points above. I'm closing this issue now, but if anything is unclear, just reopen and ask :).
