### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by wmhafiz** [keajs/kea#22]
Hi
Whats the proper setup to unit test the reducers and selectors defined in kea? do we use connect to import them in our tests? 
Thanks!

**Comment by mariusandra** [comment]
Hey, if you import any defined `const myLogic = kea({})` instance, you can access the reducers and selectors with just `myLogic.reducers`, `myLogic.selectors`, `myLogic.actions` etc. 

[Here's an example](https://github.com/keajs/kea/blob/master/src/__tests__/logic-connected.js#L70) of running tests on them.

Hope this helps :)

**Comment by wmhafiz** [comment]
excellent! thanks!
