### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by MaxOrelus** [keajs/kea#25]
Hi, I'm using `create-react-app` for my project and I followed the instructions listed in the documentation located here:

[https://kea.js.org/guide/installation](https://kea.js.org/guide/installation)

The instructions I followed was **Adding to apps made with create-redux-app**.

After running through all of the following I `npm start` my application and I'm receiving the following errors.

>> `ReferenceError: regeneratorRuntime is not defined`

I figured this might just be an issue with the `node_modules` so I removed the entire node_modules folder and went ahead and re-installed all the packages using `npm install` since everything I installed the previous time had the `--save` flag, so essentially that would give me a clean copy of all my dependencies. Still receiving the same error.

Am I missing something??

This is what my `package.json` looks like:

```json
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bulma": "^0.5.1",
    "custom-react-scripts": "^0.1.4",
    "flow-bin": "^0.52.0",
    "font-awesome": "^4.7.0",
    "history": "^4.6.3",
    "husky": "^0.14.3",
    "kea": "^0.20.8",
    "lint-staged": "^4.0.2",
    "node-sass-chokidar": "0.0.3",
    "npm-run-all": "^4.0.2",
    "prettier": "^1.5.3",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.1.2",
    "react-router-redux": "^4.0.8",
    "redux": "^3.7.2",
    "redux-saga": "^0.15.6",
    "reselect": "^3.0.1"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      "prettier --single-quote --write",
      "git add"
    ]
  },
  "scripts": {
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "flow": "flow",
    "precommit": "lint-staged",
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "devDependencies": {
    "@storybook/react": "^3.2.3"
  }
}
```

**Comment by mariusandra** [comment]
Hey, did you add the line `import "regenerator-runtime/runtime";` to the top of your index.js, as written in point 2.4 of the guide?

**Comment by MaxOrelus** [comment]
Yes, I put that in my `src/index.js`.

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mariusandra** [comment]
Ok, then the next thing to try is to add `babel-polyfill` to your package.json and add `import 'babel-polyfill'` to the top of `src/index.js`, instead of the line with `regenerator-runtime/runtime`

**Comment by MaxOrelus** [comment]
Just tried it out now. Still having the same error. Here's all my specs.

Node: v8.2.1
npm: 5.3.0

Here's copies of all my files that I had to modify according to the documentation. Am I over looking something?

`store.js`

```js
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import createSagaMiddleware from 'redux-saga';
import { keaSaga, keaReducer } from 'kea';

const reducers = combineReducers({
  scenes: keaReducer('scenes')
  // other app reducers here
});

const sagaMiddleware = createSagaMiddleware();

const finalCreateStore = compose(
  applyMiddleware(sagaMiddleware)
  // more middlewares here
)(createStore);

const store = finalCreateStore(reducers);

sagaMiddleware.run(keaSaga);

export default store;
```

`index.js`

```js
// @flow
import 'babel-polyfill';

import 'font-awesome/css/font-awesome.css';
import 'bulma/css/bulma.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import store from './store';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
registerServiceWorker();
```

`package.json`

```json
{
  "name": "cdp-app",
  "version": "0.1.0",
  "private": true,
  "contributors": [
    {
      "name": "Max Orelus",
      "email": "orelusm@america.gov",
      "url": "https://github.com/MaxOrelus"
    }
  ],
  "dependencies": {
    "babel-polyfill": "^6.23.0",
    "bulma": "^0.5.1",
    "custom-react-scripts": "^0.1.4",
    "flow-bin": "^0.52.0",
    "font-awesome": "^4.7.0",
    "history": "^4.6.3",
    "husky": "^0.14.3",
    "kea": "^0.20.8",
    "lint-staged": "^4.0.2",
    "node-sass-chokidar": "0.0.3",
    "npm-run-all": "^4.0.2",
    "prettier": "^1.5.3",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.1.2",
    "redux": "^3.7.2",
    "redux-saga": "^0.15.6",
    "reselect": "^3.0.1"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      "prettier --single-quote --write",
      "git add"
    ]
  },
  "scripts": {
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "flow": "flow",
    "precommit": "lint-staged",
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "devDependencies": {
    "@storybook/react": "^3.2.3"
  }
}
```

**Comment by kapz** [comment]
I solved this issue by ejecting and inserting the runtime requirement in the polyfis.js
If you are not scared to eject follow this steps:
1. Eject
2. Install runtime transform and decoratores
```yarn add babel-plugin-transform-runtime babel-plugin-transform-decorators-legacy```
3. Make sure your package.json has this plugins
```json
    "plugins": [
      "transform-decorators-legacy",
      [
        "transform-runtime",
        {
          "polyfill": false,
          "regenerator": true
        }
      ]
    ]
```
4. Add `require('regenerator-runtime/runtime');`to the config/polyfills.js this its executed in babel entry point

**Comment by mariusandra** [comment]
Hey, something changed with the latest `create-react-app`, released August 9th. I'm not sure what broke `regenerator` and `babel-polyfill`, but searching for the error "ReferenceError: regeneratorRuntime is not defined" gives many results of projects with similar problems.

However, it appears that the real fix was to move `kea` to use [`babel-runtime`](https://babeljs.io/docs/plugins/transform-runtime/). So starting with `0.22`, kea should work again with CRA.
