### ISSUE TITLE
Starting a new kea app from scratch with Windows does not work

### ISSUE THREAD

**Issue by Thundechile** [keajs/kea#26]
Creating a new application according documentation "Starting a new kea app from scratch" with Windows 10 gives an error about rm-command which obviously is not available from Windows command prompt.
Given command and error are as follows:
C:\temp\foobar>kea new my-project
Creating new project "my-project" with template "default" (keajs/kea-example)
--> Running: git clone --quiet --depth=1 --branch=master https://github.com/keajs/kea-example ./my-project && rm -rf ./my-project/.git
'rm' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:524
    throw err;
    ^

Error: Command failed: git clone --quiet --depth=1 --branch=master https://github.com/keajs/kea-example ./my-project && rm -rf ./my-project/.git
'rm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at Object.<anonymous> (C:\Users\foo\AppData\Roaming\npm\node_modules\kea\lib\cli\kea-new.js:50:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

**Comment by mariusandra** [comment]
Hey! Thanks for reporting!

I changed the logic in `0.22.1` to not use `rm`, but to instead remove the `.git` folder inside Node. I However as I don't have windows, I can't verify this myself. It works on a mac.

Could you confirm if it now works? Thank you :)

**Comment by Thundechile** [comment]
Verified and now seems to work with Windows also! Thanks!

**Comment by mariusandra** [comment]
Great, thanks! :)

**Comment by tapandave08** [comment]
Error: Command failed: git clone --quiet --depth=1 --branch=master https://github.com/keajs/kea-example ./myproject
'git' is not recognized as an internal or external command,
operable program or batch file.

Can you help while installing kea new my-project

**Comment by mariusandra** [comment]
Hey, you should install "git" and make sure it's available as a command line utility.

I don't use Windows and can't say what's the right approach, but probably just installing it from here will do the trick: https://git-scm.com/download/win
