### ISSUE TITLE
Example of Kea with existing redux applications

### ISSUE THREAD

**Issue by AnsonT** [keajs/kea#28]
Would be great to see how to connect Kea scenes with an existing redux applications.

**Comment by mariusandra** [comment]
Hi, when you say "kea scenes", do you mean just the kea logic stores (what you get when you call `kea()`, or do you mean the `scenes` that are defined in [scene.js](https://github.com/keajs/kea-website/blob/master/app/scenes/homepage/scene.js) for `kea-website` and the `kea-example` project that are cloned with `kea new my-project`?

If you mean the first part (`kea()` logic stores), then I have just finished a guide that explains [how to merge kea and existing redux apps](https://kea.js.org/guide/migration). If you meant the latter part (scene.js files), then there's not much I could say to be honest. That was an experimental feature which was needed when `kea` calls didn't autostart sagas and the logic stores didn't autobind. Then you could import and link all your `saga` and `logic` code into the `scene` and it would work. This is slightly deprecated and there's a reason why it's not mentioned in the docs. This entire `scenes` system will get a proper overhaul some day in the future.

But I hope you meant the first part and the [new guide](https://kea.js.org/guide/migration) will help. :)

**Comment by mariusandra** [comment]
I removed the "second part" - those old "scene.js" files and upgraded everything to use react router v4.

Let me know if the [migration guide](https://kea.js.org/guide/migration) covers what you need to know.

**Comment by AnsonT** [comment]
Thank you! Very helpful! The migration guide is exactly what I'm looking for.
