### ISSUE TITLE
loading plugin (was: Use worker to fetch data on click?)

### ISSUE THREAD

**Issue by aderaaij** [keajs/kea#29]
At the moment I'm trying out Kea in a new project but I'm still confused about a couple of things. Maybe it is because I'm not that well-versed in Redux/Redux saga. I've got an application where I simply want to send some data json I fetched as a property. The action is called `setCurrentArticle`.
I've placed the actual fetch call in a worker function called `fetchArticleData`. Now it does fetch the data, but it keeps on looping after that. Am I missing something fundamental here?  

```
    takeLatest: ({ actions, workers }) => ({
        [actions.setCurrentArticle]: workers.fetchArticleData,
    }),

    workers: {
        * fetchArticleData(action) {
            const { setCurrentArticle } = this.actions;
            const id = action.payload.currentArticle.id;
            const url = `${apiEndpoints.root}stories-api/${id}`;
            const response = yield call(fetch, url);
            if (response.status === 200) {
                    const json = yield response.json();
                    yield put(setCurrentArticle(json));
            }
        },
    },
```

**Comment by mariusandra** [comment]
Hey, should have two actions: one to initiate the request to fetch the article and a second one to actually handle the response of your action. Plus possibly even a third one to handle the failure scenario.

In your case I'd have an action called `fetchArticle` or `fetchCurrentArticle`, that's then connected to the `fetchArticleData` worker via `takeLatest`. Then your reducer listens to the `setCurrentArticle` action, which you trigger from the worker as you do now.

Currently if you call `setCurrentArticle`, it will run the worker, and if then it successfully fetches the article, it will call `setCurrentArticle` again, triggering the endless loop.

Also, if it helps, I usually use a patter similar to this:

```js
actions: () => ({
  fetchArticleRequest: (id) => ({ id }),
  fetchArticleSuccess: (article) => ({ article }),
  fetchArticleFailure: (error) => ({ error})
}),
reducers: ({ actions }) => ({
  article: [null, PropTypes.object, {
    [actions.fetchArticleRequest]: () => null,
    [actions.fetchArticleSuccess]: (_, payload) => payload.article,
    [actions.fetchArticleFailure]: () => null,
  }],
  isLoading: [false, PropTypes.bool, {
    [actions.fetchArticleRequest]: () => true,
    [actions.fetchArticleSuccess]: () => false, 
    [actions.fetchArticleFailure]: () => false,
  }],
  error: [null, PropTypes.string, {
    [actions.fetchArticleRequest]: () => null,
    [actions.fetchArticleSuccess]: () => null, 
    [actions.fetchArticleFailure]: (_, payload) => payload.error,
  }]
}),
takeLatest: ({ actions, workers }) => ({
  [actions.fetchArticleRequest]: workers.fetchArticle
}),
workers: {
  * fetchArticle (action) {
    const { fetchArticleSuccess, fetchArticleFailure } = this.actions
    const { id } = action.payload
    // do the fetching and call either the success or failure function
  }
}
```

**Comment by aderaaij** [comment]
Ah I see, that makes sense. Thank you, this is a tremendous help. Implementing it like this works perfect and I love how readable it is.

**Comment by andriijas** [comment]
@mariusandra i find  my self repeating the isLoading quite often. What do you think of a plugin like `kea-loading`   pretty much like [dva-loading](https://github.com/dvajs/dva/tree/master/packages/dva-loading) 

See [example](https://github.com/zuiidea/antd-admin/blob/b8162060cd43d839d469ad61e926003853b606d1/src/routes/dashboard/index.js#L47) how they use it to connect to a namespaced saga, just a loading object passed to component as property.

**Comment by mariusandra** [comment]
Hey, I guess you want to track if/when a worker is running?

Here's a quick plugin that does that:

```js
import { createAction } from 'kea'
import { put, apply } from 'redux-saga/effects'
import PropTypes from 'prop-types'

const loadingStarted = createAction('@@kea-loading/loadingStarted', (path, worker) => ({ path, worker }))
const loadingStopped = createAction('@@kea-loading/loadingStopped', (path, worker) => ({ path, worker }))

const loadingPlugin = {
  name: 'loading',

  isActive (input) {
    return !!input.workers || !!input.start
  },

  mutateReducerObjects (input, output, reducerObjects) {
    if (output.activePlugins.loading) {
      const initialState = {}
      const joinedPath = output.path.join('.')

      Object.keys(input.workers).forEach(key => {
        const worker = input.workers[key]
        input.workers[key] = function * () {
          yield put(loadingStarted(joinedPath, key))
          yield apply(this, worker, arguments)
          yield put(loadingStopped(joinedPath, key))
        }
        initialState[key] = false
      })

      reducerObjects.loading = {
        type: PropTypes.object,
        value: initialState,
        reducer: (state = initialState, action) => {
          if (action.type === loadingStarted.toString() && action.payload.path === joinedPath) {
            return Object.assign({}, state, { [action.payload.worker]: true })
          }
          if (action.type === loadingStopped.toString() && action.payload.path === joinedPath) {
            return Object.assign({}, state, { [action.payload.worker]: false })
          }
          return state
        }
      }
    }
  }
}

export default loadingPlugin
```

It adds a reducer `isLoading` to affected logic stores, which is an object with the worker names as keys and booleans as values.

I haven't tested it much and it's bound to break for some situations... but it's a start :). Add it to your `getStore({ plugins: [] })` array or locally to any logic store that you want to use it on.

I might convert it into an actual plugin package some day... unless someone does it first :).
