### ISSUE TITLE
Unit test console error

### ISSUE THREAD

**Issue by danielmariz** [keajs/kea#36]
I'm having this error on my console
```
console.error node_modules/kea/lib/scene/store.js:278
    [KEA-LOGIC] Path starting with "components" is not connected to the reducer tree! Make sure to call keaReducer() before any calls to kea() take place! [ 'components', 'auth', 'index' ]
```
I've tried following your tests by doing this
```
import {keaReducer} from 'kea';
const scenesReducer = keaReducer('components');
let reducerState1;
beforeEach(() => {
  reducerState1 = scenesReducer({}, { type: 'discard' });
});
it('should connect to reducer tree', () => {
  expect(reducerState1).toEqual({});
});
```

how can I fix it?

Another issue is testing using constants

## Logic:
```
export default kea({
  path: () => ['components', 'auth', 'index'],
  constants: () => [ 'LOGIN_REQUEST'],
  actions: ({constants}) => ({
    requestLogin: creds => ({
      type: constants.LOGIN_REQUEST,
      creds
    })
  })
})
```

## Test:
```
  it('should create an action to request login', () => {
        const credentials = {
            username: 'test@example.com',
            password: 'test123'
        };

        const expectedAction = {
            type: constants.LOGIN_REQUEST,
            payload: {
                creds: credentials
            } 
        };

        expect(actions.requestLogin(credentials)).toEqual(expectedAction);
    });
```

### Console error:
```
Difference:
    
    - Expected
    + Received
    
    @@ -2,8 +2,9 @@
       "payload": Object {
         "creds": Object {
           "password": "test123",
           "username": "student4@example.com",
         },
    +    "type": "LOGIN_REQUEST",
       },
    -  "type": "LOGIN_REQUEST",
    +  "type": "request login (components.auth.index)",
     }
```
So the constant is inside the payload and the action type follow the action name.
So I was wondering why it can't match the constant in this case?

Thank for your support

**Comment by mariusandra** [comment]
Hi,

I added the test you wrote to the `kea-example` repository [here](https://github.com/keajs/kea-example/blob/master/__tests__/kea.js) and when I run `yarn test`, it passes fine without errors. So I'm not sure what and how to fix for you. It seems to work fine. Can you provide more details about your situation?

For the second issue, constants are not meant to be used as types for actions. They are used more to define enums and the like. E.g. the reducer `visibilityFilter` can return either `constants.SHOW_ALL` or `constants.SHOW_ACTIVE`. 

All actions automatically get unique types generated for them from the path and their key (`request login (components.auth.index)` in your case).

Hope this helps :).

**Comment by danielmariz** [comment]
Got it, thanks for the support
