### ISSUE TITLE
Hot reloading =>  Already created action xxx

### ISSUE THREAD

**Issue by bkniffler** [keajs/kea#37]
When I use hot reloading for react, whenever it fires, koa will throw this error `[KEA-LOGIC] Already created action "set group (app.materials)"` for each action. Also, the actions will not work from then on, only on a hard reload F5 of the website it'll work again.

I wonder if you could change the behaviour of kea to overwrite actions so this works, or do you have another idea how to resolve this?

**Comment by bkniffler** [comment]
Tried to work around this by using `clearActionCache`, but now the actions will not connect to their reducers properly, also it seems like it will still use the old actions instead of hot reloaded ones. 

Any ideas how to get hot reloading working?

**Comment by mariusandra** [comment]
Hey @bkniffler, I see you closed the issue. Did you get this working somehow?

**Comment by bkniffler** [comment]
Sorry @mariusandra, I've only been evaluating kea and decided to go with pure redux for now. Its possible that my issue was due to my babel/webpack/hot-reloading setup, since else I wouldn't be the first reporting this (I guess).

**Comment by mariusandra** [comment]
I've sometimes run into the duplicate actions error as well, but usually they continue working after the HOT reload finishes. There's probably some bug there that should be fixed.

However, may I ask as feedback, what made you decide to go for pure redux in the end?

**Comment by bkniffler** [comment]
I wanted to use kea as a tool to inject middleware and reducers dynamically, but I feel like it is slightly too complex and clever and it has some syntactic sugar compared to using raw redux/reselect that leads slightly away from the default syntax.

I understand that kea is meant as a unified data-management tool, but for now, I want to work with the bare metal instead of using an all-in-one solution that introduces things I might not need. I think that reselect/redux + apollo/graphql will be enough. I will be writing a small custom library to allow injecting reducers/middleware to redux (for code splitting) and use react-redux connect to get my selectors going, and react-apollo to get data.
