### ISSUE TITLE
Separate CLI from core library

### ISSUE THREAD

**Issue by rheng** [keajs/kea#38]
Currently `commander` is listed as a dependency. Would it make more sense to move this and other CLI related libs into a separate repo `kea-cli` so these do not get bundled with production builds?

Also, is there a reason why this library is including a specific hash?
 `tj/commander.js#c6236d9504b60d9a2e6aa7fc3ce17a12f48f4a3e`
It is giving me issues when trying to add it with yarn behind a corporate proxy.

Thanks!

**Comment by mariusandra** [comment]
Hey, that's a great idea and I have thought about doing that for a while.

I published a new package, `kea-cli` on NPM. It's a `v0.24` and will try to keep version parity with the main `kea` package.

I'll release `0.24` of the main `kea` package later today, which will have the CLI code ripped out.

**Comment by mariusandra** [comment]
Hi, `0.24.1` is out without the CLI tools. Please let me know that fixes the issue you had :)

**Comment by rheng** [comment]
Wow that was quick! Works great now, thanks. Awesome project 👍  🐦
