### ISSUE TITLE
Kea with Preact?

### ISSUE THREAD

**Issue by hwclass** [keajs/kea#39]
Hey folks,

I've just trying to differentiate Kea with some other frameworks/libraries using Redux as a base but could not find any source using preact as its view layer integrated with Preact. Is there any plan to do such an example and step-by-step guide using Kea with Preact?

Update: I have tried with a sample app and got he following:
```
ERROR in ./~/kea/lib/kea/index.js
Module not found: Error: Can't resolve 'react-redux' in '/<repo-path>/node_modules/kea/lib/kea'
 @ ./~/kea/lib/kea/index.js 52:18-40
 @ ./~/kea/lib/index.js
 @ ./src/containers/some-container.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src
```
Note: <i>I am using preact-redux.</i>

Cheers

Baris

**Comment by mariusandra** [comment]
Hey,

I'm definitely up for having better compatibility and documentation in regards to integrating with preact and inferno (and others?). 

The only line of code that can possibly have issues is the same one you stumbled on:

```
import { connectAdvanced } from 'react-redux'
```

So the first question: if you alias "react-redux" to "preact-redux" in your webpack conf (assuming you're using webpack), will that make it work?

If no other code change is required, then we have a few options going forward:
1) State in the installation instructions that you use do this alias
2) Build separate versions of kea for react, preact and inferno, similar to how I did with [pigeon-maps](https://github.com/mariusandra/pigeon-maps/issues/1)
3) Replace the line with something like:

```js
let connectAdvanced
try {
  connectAdvanced = require('react-redux').connectAdvanced
} catch (e) {
  connectAdvanced = require('preact-redux').connectAdvanced
}
```

All of these options have their pros and cons... but the first step is to see if it works with the alias. Could you test it? 

Thanks :)

**Comment by mariusandra** [comment]
Hi, as I read from here: https://github.com/developit/preact/issues/863 
... kea works fine with Preact. So closing this issue.
