### ISSUE TITLE
Separate Kea from Redux Saga

### ISSUE THREAD

**Issue by johntran** [keajs/kea#44]
Hi there!

I'm using Kea at work with Relay Modern and I noticed that Kea has a dependency on Redux Saga. I think it would be better to have the Redux Saga support as a separate package in case that a user has a different async library.

**Comment by mariusandra** [comment]
Hey!

I fully agree with this. In fact, work on it has already started with issue #40. The first step in implementing redux-observable support is to put the redux-saga support in a separate package. Work in this is slow for now, yet I still expect most of it done by the end of this month.

Thank you for your support and patience! :)

**Comment by mariusandra** [comment]
Hey, starting with `v0.25`, [`kea-saga`](https://github.com/keajs/kea-saga) is now a separate package and all redux-saga code has been ripped out of the main package.

I also added a [kea-thunk](https://github.com/keajs/kea-thunk) package.
