### ISSUE TITLE
connect - import all the props from a reducer?

### ISSUE THREAD

**Issue by amitava82** [keajs/kea#47]
Two questions,
1. How do I import everything from a reducer/actions?
2. put them into it's own object instead of everything in `this.props`

Eg,
```
// if task reducer had following properties
{
  data: [],
  loading: false
}

@connect({
  actions: [
    session, ['storeSession'],
    tasks, ['*']
  ],
  props: [
    session, ['isLoggedIn'],
    tasks, ['*']
  ]
})

//somewhere in component, I should be able to use like this:
this.props.tasks.data;
this.props.tasks.loading
this.props.session.isLoggedIn
this.actions.session.login();
this.actions.tasks.load();
```

**Comment by mariusandra** [comment]
Hey!

As of `0.25.1`, you can import all the reducers from a logic store with `"* as x"`, so:

```js
@connect({
  props: [
    session, ['isLoggedIn'],
    tasks, ['* as tasks']
  ]
})

// giving you:
this.props.tasks.data
this.props.tasks.loading
this.props.isLoggedIn
```

Unfortunately as of this point there's nothing similar for actions, but I'll keep the issue open and I'll keep the issue open until I manage to add it (or someone else sends a PR :)). I'm currently busy with some bigger refactoring and code cleanups in preparation for `redux-observable` support and will investigate this once that's done.

As for selecting specific props and adding them to their own objects, like `session.isLoggedIn`, it's currently not possible and I'm slightly hesitant to add it, as it will increase the complexity of the library. If needed and facing naming conflicts, you can still rename the props when importing, like so: `props: [ session, [ 'isLoggedIn as isSessionLoggedIn' ] ]`.

In general, I also recommend not loading in everything with the wildcard (`*`), as it hides what is being imported from the component.

I wrote about this in the guide about [connected logic stores](https://kea.js.org/guide/connected), but in relation to something else. It also applies to this situation:

> First, it's not clear what you're importing. As code is read far more times than it's written, it's very very useful to be as explicit as possible. Your future self will thank you immensely! In this case you have no idea what extra props and actions your component will receive without having to open features-logic.js and checking it out yourself.
>
> You also don't know what baggage you're getting. There might be hundreds of new actions and props, which your relatively simple component will receive. That will slow down the page, as a change in each of them will trigger re-rendering.
>
> What if one of the props changes? For example the new intern replaces the action toggleFeature with two new actions: setFeature and clearFeature. Without (manually or automatically) clicking the buttons, you won't know that the action is no longer there. Bummer.
> 
> What's more, you can't chain calls like this and you can't add other actions that only this component will use.

**Comment by mariusandra** [comment]
Also, if you really need the props to be in a separate object, you can always use selectors, something like this:

```js
@kea({
  connect: {
    actions: [
      session, ['storeSession'],
      tasks, ['*']
    ],
    props: [
      session, ['isLoggedIn'],
      tasks, ['*']
    ]
  },
  selectors: ({ selectors }) => ({
    session: [
      () => [selectors.isLoggedIn],
      (isLoggedIn) => ({ isLoggedIn }),
      PropTypes.object
    ]
  })
})
```

**Comment by mariusandra** [comment]
Hey, I thought about it decided against supporting `"* as x"` in actions.

It would make the library needlessly complicated, as actions are bound to `dispatch` functions all over the place, in kea and in most plugins (saga, thunk). Requiring an extra "if action is an object, bound the values of the object, not the object itself" check everywhere in kea, and forcing all plugin creators/maintainers to adopt this edge case is just not worth it, IMHO.

So the official answer to your initial questions are:

1. For props, use `"* as everything"`, for actions it's not possible.
2. You may use a selector to group the props in whichever way you like. For actions, it's not possible.

As every additional feature requires a lot of invisible maintenance overhead, I try to be prudent against code creep. Sorry, and I hope you understand :).
