### ISSUE TITLE
Router (ReactRouter V4) nested inside a kea connected component does not work

### ISSUE THREAD

**Issue by AnsonT** [keajs/kea#49]
Connecting Kea to a component that contains routes does not work properly, the routes are not matched. 

```javascript
import React,  { Component } from 'react'
import { kea } from 'kea'

const logic = kea({})

class _Wrapper extends Component {
  render() {
    return(
      <div>{this.props.children}</div>
    )
  }
}

const Wrapper =  logic(_Wrapper) // switch routes does not work
//const Wrapper = _Wrapper  // switch routes works

const App = () => (
  <ConnectedRouter history={history}>
    <Wrapper>
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/foo">Foo</Link></li>
        <li><Link to="/bar">Bar</Link></li>        
      </ul>
      <Route exact path="/" component={Home} />
      <Route path="/foo" component={Foo} />
      <Route path="/bar" component={Bar} />
    </Wrapper>    
  </ConnectedRouter>
)
```

**Comment by mariusandra** [comment]
Hi, is this a bug unique to Kea, or is the same true with any regular Redux `Connect`'ed component?

**Comment by AnsonT** [comment]
This is not a KeaJS issue:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by mariusandra** [comment]
Great, thanks for reporting back! :)

**Comment by nikolakanacki** [comment]
@mariusandra I would pin this somehow somewhere (on the website even, docs, FAQ, if its not already) since many users facing this might give up on the lib thinking it's whats causing the issue.

**Comment by mariusandra** [comment]
I'm opening this issue again and will close once I manage to add it to a FAQ page.
Or if anyone else is willing to do it, feel free! Look at the keajs/kea-website repository.

**Comment by AnsonT** [comment]
Added an FAQ section for this issue in this PR:
https://github.com/keajs/kea-website/pull/5

**Comment by mariusandra** [comment]
Very cool, thank you! :+1:

I merged your changes and added an example to the end that solves the issue of depending on the location in a *kea-esque* way. That's the approach that [the header of the website](https://github.com/keajs/kea-website/blob/master/app/components/header/index.js#L80) also uses.
