### ISSUE TITLE
Looking to integrate with Redux-PouchDB-Plus

### ISSUE THREAD

**Issue by AnsonT** [keajs/kea#53]
I'm looking at using redux-pouchdb-plus for persistence. The integration requires wrapping persistentReducer around reducers to be saved to the db. Looking for suggestions on how to do that with reducers generated by Kea.

**Comment by mariusandra** [comment]
Hey, up until `0.26`, kea had built in support to store reducers in LocalStorage. From `0.27`, I removed this support and extracted it into a [kea-localstorage](https://github.com/keajs/kea-localstorage) plugin.

I guess the code to support pouchdb would work in a similar way. Feel free to have a crack at it! :)

**Comment by AnsonT** [comment]
I see how mutateReducerObjects would work for the pouchDB scenario. It seems like a generally useful facility to be able to filter and mutate reducers.
