### ISSUE TITLE
Why so large?

### ISSUE THREAD

**Issue by amrdraz** [keajs/kea#55]
Kea provides a very concise way of collecting application logic, making it a really tempting framework to operate on,  but why are its plugins so large?

<img width="806" alt="screen shot 2017-10-25 at 19 48 09" src="https://user-images.githubusercontent.com/1708559/32014177-9bfa354c-b9bd-11e7-9fc1-cf966a319aa9.png">

In the previous image I included all packages even though I intend to only include thunk
but even still how can a mere wrapper have the same size as kea itself.

it makes some sense for kea being 21kb gzipped ; however the numbers I'm seeing suggests that kea could be suffering from maybe bad bundling, or at least the async plugins.

just wondering

**Comment by mariusandra** [comment]
Hi, indeed there is some bad bundling.

I managed to get the `kea` repo and `kea-thunk` down a bit. Tomorrow I'll finish the work and do the same for `kea-saga`. Off to sleep now :).

<img width="539" alt="screen shot 2017-10-26 at 00 02 28" src="https://user-images.githubusercontent.com/53387/32025559-fc39f91a-b9e0-11e7-9015-c46cc26c33fb.png">

**Comment by mariusandra** [comment]
Hi, I just released `0.27` and these are the results I get in vscode: 

<img width="524" alt="screen shot 2017-10-26 at 10 20 16" src="https://user-images.githubusercontent.com/53387/32042416-b26dd78c-ba37-11e7-8934-8ad0508c274b.png">

If I look at the `kea-website` project through the `webpack-montor` plugin, I see this:

<img width="819" alt="screen shot 2017-10-26 at 10 21 47" src="https://user-images.githubusercontent.com/53387/32042413-af1fefde-ba37-11e7-9426-1ab39d0171b1.png">

<img width="819" alt="screen shot 2017-10-26 at 10 22 00" src="https://user-images.githubusercontent.com/53387/32042406-a7e17d46-ba37-11e7-8891-ccd9b68a0cc2.png">

I guess the big size of `kea-saga` on the vscode screenshot also includes `redux-saga` (62KB).

Somehow `regenerator-runtime` is included twice in the pie chart. Once through `babel-runtime` and once on its own. I'm not sure what's happening there.

It's all a bit less than before, but there's still certainly room for improvement. If anyone has great ideas, I'm all ear! :)

**Comment by amrdraz** [comment]
the extent of my interest died with kea-thunk since that's what I intend to use and am very happy with the result 😅 

I'm very  happy kea itself got smaller, this is not longer a pressing problem for me and is outside of my immediate knowledge, so I can't help without investing time, I would be very pleased to learn from whomever suggests something.

**Comment by mariusandra** [comment]
Great! Closing the issue for now. If anyone has anything to add about the bundle sizes, feel free to reopen or make a new issue.

**Comment by mariusandra** [comment]
For completion, I'm adding this update.

Something changed with the way the vscode plugin calculates sizes. Now for me it shows:

<img width="523" alt="screen shot 2018-01-26 at 13 01 09" src="https://user-images.githubusercontent.com/53387/35438958-13d85746-0299-11e8-84fa-96cd3f4c398b.png">

... which seems more or less reasonable. 

I think the sizes for `kea-saga` (29.9k) and `kea-thunk` (1.5k) already include `redux-saga` (21.5k) and `redux-thunk` (0.8k). There's no way `kea-saga` adds 30k of code on its own :).
