### ISSUE TITLE
Is kea compatible with redux-offline?

### ISSUE THREAD

**Issue by alp82** [keajs/kea#61]
[redux-offline](https://github.com/redux-offline-team/redux-offline) is a toolset that enriches redux definitions with meta data (like kea does). It has offline-persistence capabilities and encourages optimistic ui patterns.

Is there a way to use redux-offline with kea or would that be a difficult task?

**Comment by mariusandra** [comment]
Hi, it doesn't work out of the box. I'm sure it can somehow be implemented through plugins, but I have no time to work on it now. Feel free to have a crack at it!

Right now for "offline" support there is a plugin called [kea-localstorage](https://kea.js.org/plugins/localstorage) that stores reducers in the browser's LocalStorage and there's some discussion [here](https://github.com/keajs/kea/issues/53) about integrating PouchDB. 

I realise that `redux-offline` offers much more (e.g. write-resiliance when the network is down), but the above links might be starting points in exploring this further.
