### ISSUE TITLE
thunks are broken

### ISSUE THREAD

**Issue by stefan-matmatch** [keajs/kea#62]
While trying to migrate our existing redux app it is crucial to have access to "outside kea" state in actions. Currently the only way would be to use `getState` in the thunk plugin.
Unfortunately there is no way to get them working right now.

Not even the proposed solution from [this issue](https://github.com/keajs/kea/issues/60) is working.

**Comment by mariusandra** [comment]
Hi,

1) I replied in [that issue](https://github.com/keajs/kea/issues/60) about a way to get it working. Please check if that can help you. If not, please report back and I'll try something else :)

2) For accessing external state, have you looked at this guide: https://kea.js.org/guide/migration

If you get the thunk plugin working and connect to your external state via the `connect` keyword, then inside the thunk functions you should be able to access your external state via the `get` and `fetch` functions inside your thunks. Something like:

```js
const logic = kea({
  connect: {
    props: [
      (state) => state.router, [
        'location'
      ]
    ]
  },
  actions: ({ constants }) => ({
    updateName: name => ({ name })
  }),
  thunks: ({ actions, dispatch, getState, get, fetch }) => ({
    updateNameAsync: name => {
      const { pathname } = get('location')
      // ...
    },
  })
})

**Comment by stefan-matmatch** [comment]
Hi,
thanks for getting back!
I really do believe in your lib & are trying to convince my team to migrate ;)

When using `import 'kea-thunk/install' `, the `output.activePlugins` in `afterCreateSingleton` method are undefined...

**Comment by mariusandra** [comment]
Which version of the packages are you using?

**Comment by mariusandra** [comment]
Hey, here hare a few points I can think of. I'm not sure if they apply to your situation, so please confirm or deny them.

1. Try upgrading `kea` and `kea-thunk` to the latest versions

2. Make sure that either `import 'kea-thunk/install'` or this `activatePlugin()` is run before any call to `kea({})` and before the call to `getStore()` takes place. 

3. If your logic store does not us any thunks (the `thunks: () => ({})` object is empty), then `output.activePlugins` will not include the thunk. So make sure that for the logic store you're debugging this on, you also have some thunks :).

Here's also a [webpackbin](https://www.webpackbin.com/bins/-KxSPoMw6q-_lcXY8guq) you can play around with if it helps anything.

**Comment by stefan-matmatch** [comment]
1 : before upgrade:
     "kea": "^0.26.6",
    "kea-thunk": "^0.3.0"
   after:
    "kea": "^0.27.2",
    "kea-thunk": "^0.3.2",

2. taken care of

3. thunks r in place :)

Currently trying to prove the error in the bin you provided. Thanks a bunch for the support!

**Comment by mariusandra** [comment]
Somehow I can understand the issues you had before, as:

* kea-thunk 0.3 works with kea 0.27+
* kea-thunk 0.2 works with kea 0.26
* kea-thunk 0.1 works with kea 0.25

... but it should work now... somehow :)

**Comment by stefan-matmatch** [comment]
Your `0.27.03` update to npm fixed it :)

**Comment by mariusandra** [comment]
Great! :)
