### ISSUE TITLE
Cannot resolve `reselect`

### ISSUE THREAD

**Issue by johntran** [keajs/kea#66]
Steps:

1. `rm -rf node_modules yarn.lock`
2. `yarn add kea`
3. Build app

Get following error:
`Module not found: Error: Can't resolve 'reselect' in '~/node_modules/kea/es/kea/logic'`

Same thing happens if using `npm i`.

When I do `yarn add reselect`, the issue is gone.

**Comment by mariusandra** [comment]
Hi, that's why the docs ([here](https://kea.js.org/guide/installation) and [here](https://github.com/keajs/kea)) advocate doing:

```js
yarn add kea redux react-redux reselect
```

:)

**Comment by johntran** [comment]
Ah, I see. I thought selectors were an optional thing for `kea`, but it's actually a pretty important feature. Totally overlooked that :). Thanks!
