### ISSUE TITLE
[feature] subscribe to logic store

### ISSUE THREAD

**Issue by amrdraz** [keajs/kea#68]
While there seems to be work on using redux observable #40 would a general observable API integration in kea logic stores be a good idea?

currently connect does the job of connecting kea logic stores with components
but parts of application logic such as services would need to subscribe to either selectors or actions

can therefore kea function include the option of adding listeners  that trigger actions, or/and be subscribable such as

logic.subscribe()
logic.selectors.isLoggedIn.subscribe()

etc.. will using kea-observable solve this use case?

I'm talking here about logic to logic store communication not components

currently I just use a mediator in my logic files that is fired by actions and subscribe to that

**Comment by amrdraz** [comment]
how did I open and close this 😅

**Comment by mariusandra** [comment]
Hey, well, Kea is just a wrapper around Redux, so if you want to subscribe to notifications, it's best to find some *Reduxy* way, such as writing a Redux middleware.

Another option is to get ahold of the [`store`](https://kea.js.org/api/store) and call `store.subscribe()`, as described in the [redux docs](https://github.com/reactjs/redux#the-gist).
