### ISSUE TITLE
Working with highly normalized data

### ISSUE THREAD

**Issue by ChrisLincoln** [keajs/kea#78]
I have this type of object hierarchy which is stored in an RDBMS in a highly-normalized fashion. The REST-ish API also serves up data in a highly normalize form.

item -> has a foo -> has a bar -> has a....

In other words, given item X, I can walk his foreign key relationship path out to the "bar" entity and display X's bar fields.  "foo" and "bar" are massive tables that can't be pulled down to the client in their entirety. The API provides individual GET /foo/{id} and GET /bar/{id}.  I would like to be able 
a) only make those GET requests when a component rendering "item" is in view and 
b) cache the request results to cut down on unneeded traffic.

I am just hours into learning about memoized selectors, and I know I really have a reselect question, not a kea question.  But I want to know if the solution provided in the Dynamic Counters example is the Kea-way of using a selector factory as outlined here: [https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-component-instances](https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-component-instances). 

My mental model was to just having a store for "foo", that kept a collection of foo, and provided a lookup/request-if-not-found model.  I am stuck at figuring out how to at the component level ask for a paticular "Foo".

Should I follow the pattern in the Dynamic Counters or apply one from the provided link?

**Comment by mariusandra** [comment]
Hey,

Here's one solution. It might not be the most elegant, but it should work.

It pushes the responsibility of fetching foo and bar down to the component that renders Item.

```js
const itemLogic = kea({
  actions: () => ({
    fetchItem: (id) => ({ id }),
    itemsLoaded: (items) => ({ items })
  }),
  reducers: ({ actions }) => ({
    items: [{}, PropTypes.object, {
      [actions.itemsLoaded]: (state, payload) => ({ ...state, normalise(payload.items) }),
      [actions.fetchItem]: (state, payload) => ({ ...state, [payload.id]: { _loading: true } })
    }]
  }),
  selectors: ({ selectors }) => ({
    itemsArray: [
      () => [selectors.items],
      (items) => Object.values(items),
      PropTypes.array
    ]
  }),
  takeEvery: ({ actions }) => ({
    [actions.fetchItem]: function * () {
      // saga code to GET the item and return it via
      // yield put(this.actions.itemsLoaded({ [item.id]: item }))
    }
  })
})

const fooLogic = // similar to the above
const barLogic = // similar to the above]

// all of this could be extracted to a createModel() function similar to
// the createForm function in the forms kea guide example
```

Then in your component

```js
@connect({
  props: [
    itemLogic, [
      'itemsArray as items'
    ]
  ]
})
const MainComponent = (props) => (
  <div>
    {props.items.map(item => <Item key={item.id} item={item} />)}
  </div>
)

@kea({
  propTypes: {
    item: PropTypes.object.isRequired
  },
  connect: {
    props: [
      fooLogic, [
        'foos'
      ],
      barLogic, [
        'bars'
      ]
    ],
    actions: [
      fooLogic, [
        'fetchFoo'
      ],
      barLogic, [
        'fetchBar'
      ]
    ]
  },
  selectors: ({ selectors }) => ({
    foo: [
      () => [(_, props) => props.item, selectors.foos],
      (item, foos) => item.foo ? foos[item.foo] : null,
      PropTypes.object
    ],
    bar: [ .. similar .. ]
  }),
  start: function * () {
    const { fetchFoo, fetchBar } = this.actions
    const { foo, bar } = yield this.fetch('foo', 'bar')
    const { item } = this.props
    if (!foo && item.foo) {
      yield put(fetchFoo(item.foo))
    }
    if (!bar && item.bar) {
      yield put(fetchFoo(item.bar))
    }
  }
})
const Item = ({ item, foo, bar }) => (
  <div>
    <div>Item {item.id}</div>
    {foo && !foo._loading ? (<div>Foo {foo.id}</div>) : null}
    {bar && !bar._loading ? (<div>Bar {bar.id}</div>) : null}
  </div>
)
```

**Comment by ChrisLincoln** [comment]
Got it.  I think I can make that work.
