### ISSUE TITLE
Tests started failing with connected logics

### ISSUE THREAD

**Issue by kapz** [keajs/kea#82]
I've been using Kea for some months now, I came across this issue.
My logic tests all started failing when logics are connected to another.
It seems it receives the connected logic as undefined

```TypeError: Cannot read property '_isKeaSingleton' of undefined```

on the function

```connectLogicIfUnconnected (node_modules/kea/lib/kea/connect/mapping.js:9:12)```

Thanks!

**Comment by tonyhb** [comment]
I've seen something similar to this before and for me it meant that I was defining Kea reducers etc. before the store is configured - because my import order was incorrect.

Maybe that helps you

**Comment by mariusandra** [comment]
@kapz could you share some code that fails?

The error points to a situation where whatever you passed as the logic to `connect` is not defined. 

Taking a guess in the dark: could you have some cyclical importing happening?

I mean something like:

```js
// a.js
import b from './b.js'
@connect({ props: [b, ['propFromB']] })
export default (props) => <div>{props.propFromB}</div>

// b.js
import a from './a.js'
@connect({ props: [a, ['propFromA']] })
export default (props) => <div>{props.propFromA}</div>
```

If yes, then you'll need to refactor it as cyclical code loading graphs are just not possible in webpack.

**Comment by kapz** [comment]
@mariusandra Sorry for the delay, yes. The problem has cyclical imports, the only weird thing is it only failed on tests.
But refactoring solved the issue.
