### ISSUE TITLE
get "Cannot read property 'render' of undefined" error when my 'App' Component is a fat arrow function

### ISSUE THREAD

**Issue by lgy87** [keajs/kea#86]
```
function isStateless(Component) {
  return !Component.prototype.render;
}
```

when i type this:
```
const logic = kea({})
const App = props => {}
export default logic(App)
```

i got:
> Uncaught TypeError: Cannot read property 'render' of undefined
>     at isStateless (index.js:23)

a normal function is ok.

**Comment by dlasky** [comment]
@lgy87 this should be all set now.

**Comment by lgy87** [comment]
Thanks for your work, i will close the issue.
